name:                docent
version:             0.1.0.0
github:              "ashokkbhaskar/docent"
license:             AGPL-3.0-or-later
author:              "Ashok Kasi Bhaskar"
maintainer:          "ashok@bhaskars.com"
copyright:           "2020 Ashok Kasi Bhaskar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ashokkbhaskar/docent#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  docent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docent

tests:
  docent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - docent
